config/routes.rb
RedcrossTrackr::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :chapters
  resources :locations do
    resources :items do
      match "give/" => "items#give", :as => :give
      match "lend/" => "items#lend", :as => :lend
    end
  end

  root :to => 'locations#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  class IsNotContainerableException < RuntimeError; end

  attr_accessible :name, :quantity, :container_id, :item_id, :description,
                  :item_type_definition_id, :home_location_id, :current_location_id,
                  :picture, :picture_cache, :remove_picture, :item_type_definition,
                  :current_location, :home_location, :item_field_values_attributes


  belongs_to :item_type_definition
  belongs_to :home_location, :class_name => "Location"
  belongs_to :current_location, :class_name => "Location"
  belongs_to :container, :class_name => "Item"

  # has_many :contained_items, :class_name => "Item"
  # has_many :item_fields

  has_many :item_field_values
  accepts_nested_attributes_for :item_field_values

  delegate :item_type_fields, :to => :item_type_definition

  mount_uploader :picture, PictureUploader

  validates_presence_of :name

  scope :containers, joins(:item_type_definition).where("item_type_definitions.kind_id" => Kind.find_or_create_by_name("container").id)
  scope :individuals, joins(:item_type_definition).where("item_type_definitions.kind_id != " + Kind.find_or_create_by_name("container").id.to_s)
  scope :of_type, lambda { |item_type_definition| where(:item_type_definition_id => item_type_definition.id) }

  def at_home?
    current_location == home_location
  end

  def items
    if is_containerable
      contained_items
    else
      []
    end
  end

  def move_some_items_to(location, options)
    decrease_quantity_by(options[:quantity])
    Item.create!(
      name: self.name,
      item_type_definition: self.item_type_definition,
      quantity: options[:quantity],
      home_location: location,
      current_location: location
    )
  end

  def decrease_quantity_by(amount)
    self.quantity -= amount
    save!
  end

  def give_all_items_to(location)
    self.update_attributes!(home_location: location, current_location: location)
  end

  def lend_all_items_to(location)
    self.update_attributes!(current_location: location)
  end

  def give(qty, location, container)
    if container.is_a?(Item)
      give_all_items_to(container.current_location)
      self.home_location = container.current_location
      self.current_location = container.current_location
      self.container = container
    elsif container.is_a?(Location)
      give_all_items_to(location)
      self.home_location = location
      self.current_location = location
      self.container = nil
    else
      give_all_items_to(location)
      self.home_location = location
      self.current_location = location
      self.container = nil
    end
    save!
  end

  def lend(qty, location, container)
    if container.is_a?(Item)
      lend_all_items_to(container.current_location)
      self.current_location = container.current_location
      self.container = container
    elsif container.is_a?(Location)
      lend_all_items_to(location)
      self.current_location = location
      self.container = nil
    else
      lend_all_items_to(location)
      self.current_location = location
      self.container = nil
    end
    save!
  end


end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_paranoid
  geocoded_by :full_address
  after_validation :geocode

  attr_accessible :address, :address2, :city, :state_id, :zip,
                  :name, :description, :chapter_id, :state,
                  :contact_name, :contact_phone,
                  :national_shelter_system_identifier,
                  :picture, :picture_cache, :remove_picture

  attr_accessible :address, :address2, :chapter_id, :city, :contact_name, :contact_phone, :name, :national_shelter_system_identifier, :state_id, :zip, :chapter

  validates_presence_of :name, :address, :city, :state, :zip, :chapter
  validates_uniqueness_of :national_shelter_system_identifier, :allow_blank => true

  belongs_to :state
  belongs_to :chapter
  has_many :items, :foreign_key => "current_location_id"

  before_destroy :abort_delete_if_location_has_items

  mount_uploader :picture, PictureUploader

  def full_address
    [address, address2, city, state.name, zip].compact.join(" ")
  end

  def contact?
    contact_name.present? or contact_phone.present?
  end

  def number_of_items_of_type(item_type_definition)
    items.of_type(item_type_definition).sum("quantity")
  end

private
  def abort_delete_if_location_has_items
    return false if items.any?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_location

  def index
    # @locations = Location.all
  end

  def show
    @item = @location.items.find(params[:id])
  end

  def new
    @item = Item.new(:home_location => location, :current_location => location)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    # @location = Location.new(params[:location])
    # if @location.save
      # redirect_to @location, notice: 'Location was successfully created.'
    # else
      # render action: "new"
    # end
    #

    @item = Item.new(params[:item])

    if @item.save
      redirect_to @location
    else
      render action: "new"
    end

  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to location_item_path(@location, @item), notice: 'Item was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    # @location = Location.find(params[:id])

    # if @location.destroy
    #   redirect_to locations_url
    # else
    #   redirect_to edit_location_path(@location), alert: "Can't delete this location because it has items attached to it."
    # end
  end

  def give
    @errors = []
    @items = [].push @location.items.find(params[:item_id])
    if request.post?
      location = Location.find(params[:item][:location_id])
      container = location.items.find_by_id(params[:item][:container_id])
      @items.zip(params[:quantities]).each do |item, qty|
        if (qty.to_i < item.quantity.to_i) && (qty.to_i > 0)
          old_item = item
          old_item_attributes = old_item.attributes
          old_item_attributes.delete("id")
          old_item_attributes.delete("created_at")
          old_item_attributes.delete("updated_at")
          new_item = Item.new(old_item_attributes)
          old_item.quantity = item.quantity.to_i - qty.to_i
          old_item.save!
          new_item.quantity = qty.to_i
          new_item.give(qty, location, container)
        elsif qty.to_i == item.quantity.to_i
          item.give(qty, location, container)
        elsif qty.to_i < 0
          @errors << [item, "Can't give a negative quantity of items"]
        else
          @errors << [item,"Can't give more items than exist on the item quantity"]
        end
      end
      redirect_to @location, :notice => "Giving completed successfully!" unless @errors.any?
    end
  end


  def lend
    @errors = []
    @items = [].push @location.items.find(params[:item_id])
    if request.post?
      location = Location.find(params[:item][:location_id])
      container = location.items.find_by_id(params[:item][:container_id])
      @items.zip(params[:quantities]).each do |item, qty|
        if (qty.to_i < item.quantity.to_i) && (qty.to_i > 0)
          old_item = item
          old_item_attributes = old_item.attributes
          old_item_attributes.delete("id")
          old_item_attributes.delete("created_at")
          old_item_attributes.delete("updated_at")
          new_item = Item.new(old_item_attributes)
          old_item.quantity = item.quantity.to_i - qty.to_i
          old_item.save!
          new_item.quantity = qty.to_i
          new_item.lend(qty, location, container)
        elsif qty.to_i == item.quantity.to_i
          item.lend(qty, location, container)
        elsif qty.to_i < 0
          @errors << [item, "Can't lend a negative quantity of items"]
        else
          @errors << [item,"Can't lend more items than exist on the item quantity"]
        end
      end
      redirect_to @location, :notice => "Lending completed successfully!" unless @errors.any?
    end
  end

  def find_location
    @location = Location.find(params[:location_id])
  end
end

app/views/items/_form.html.erb
<div class="enable-items-js item-form">
  <%= form_for [location, item] do |f|%>

    <% if !item.errors.blank? %>
      <div class ="alert">
        <%= error_messages_for item %>
      </div>
    <% end %>

    <%= f.hidden_field :current_location_id, :value => location.id %>

    <% if f.object.new_record? %> 
      <%= f.label :item_type_definition_id, "Kind: " %>
      <%= f.select(:item_type_definition_id, ItemTypeDefinition.options) %>
    <% else %>
      <%= f.hidden_field(:item_type_definition_id) %>
    <% end %>

    <div class="info">
      <div>
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description %>
      </div>
      <div>
        <%= f.label :quantity, "Quantity:" %>
        <%= f.number_field :quantity %>
      </div>

      <div id="data-fields" data-additional-fields="<%= ItemFieldDefinition.definition_json %>">
      </div>

      <div id="data-field-values" data-field-values="<%= @item.item_field_values.to_json %>">
      </div>

      <div id="data-item-id" data-item-id="<%= @item.id %>">
      </div>

      <script id="fields-template" type="text/x-handlebars-template">
        {{#each fields}}
          <label for="item[item_field_values][]">{{name}}</label>
          <input type="{{kind}}" name="item[item_field_values_attributes][{{index}}][value]" id="item_item_field_values_" value="{{value}}"/>
          <input type="hidden" name="item[item_field_values_attributes][{{index}}][item_field_definition_id]" value="{{id}}"/>
        {{/each}}
      </script>

      <div id="additional_fields">
      </div>

    </div>

    <div class="actions two">
      <% if item.new_record? %>
        <%= f.submit "Create", :class => "btn btn-primary btn-large" %>
        <%= link_to "Cancel", location, :class => "btn btn-classy btn-large" %>  
      <% else %>
        <%= f.submit "Update", :class => "btn btn-primary btn-large" %>
        <%= link_to "Cancel", [location, item], :class => "btn btn-classy btn-large" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/items/_move_or_lend.html.erb
<% if @errors.any? %>
  <div class="errors alert alert-error">
    <% @errors.each do |item, error| %>
        <div class="error"><%= error %></div>
    <% end %>
  </div>
<% end %>


<% item = @items.first %>


<h2>From : </h2>
Owner : <%= item.home_location.name %><br />
Current Location : <%= item.current_location.name %><br />
Container : <%= item.container.name if item.container %><br />


<h2>To : </h2>
<label for="giving-lending-location">Location</label>
<%= select_tag "item[location_id]", options_from_collection_for_select(Location.all, :id, :name), :id=>"giving-lending-location" %>

<label>Container</label>
<% Location.all.each do |location| %>
    <%= select_tag "item[container_id]", "<option></option>".html_safe + options_from_collection_for_select( location.items.containers, :id, :name), :class=>"container-select", :id => "container-#{location.id}"  %>
<% end %>

<hr />


<div class="item">
    <%= hidden_field_tag "item_ids[]", item.id %>
    <%= (image_tag item.picture_url(:thumbnail), :alt => item.name) if item.picture.present? %>
    <%= link_to item.name, [@location, item] %>
    <%= item.item_type_definition.name %>
    <%= item.quantity %>
    <%= item.container.name if item.container %>

    <%= text_field_tag "quantities[]", item.quantity, :type => "number" %>
</div>

app/views/items/create.html.erb
Happy

app/views/items/edit.html.erb
<h3>Edit Item</h3>

<%= render :partial => "form", :locals => {:location => @location, :item => @item} %>

app/views/items/give.html.erb
<h1>Give Item : </h1>

<%= form_tag location_item_give_path(@location) do %>
  <%= render "move_or_lend" %>
  <%= submit_tag "Give Items" %>
<% end %>

app/views/items/lend.html.erb
<h1>Lend Item : </h1>

<%= form_tag location_item_lend_path(@location, @items) do %>
  <%= render "move_or_lend" %>
  <%= submit_tag "Lend Items" %>
<% end %>

app/views/items/lend_success.html.erb
Lend completed successfully!

app/views/items/new.html.erb
<h3>Add Item</h3>

<%= render :partial => "form", :locals => {:location => @location, :item => @item} %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @item.name %></h1>

<%= (image_tag @item.picture_url(:thumbnail), :alt => @item.name) if @item.picture.present? %>

<div class="address">
  <%= @item.quantity %> x <%= @item.item_type_definition.name %>

  <% if @item.container %>
    <br/>Container: <%= @item.container.name %>
  <% end %>

  <br/>Home Location: <%= @item.home_location.name if @item.home_location %>
  <% unless @item.at_home? %>
    <br/>Current Location: <%= @item.current_location.name %>
  <% end %>
</div>

<div class="actions three">
  <%= link_to "Give", location_item_give_path(@location, @item), :class => "btn btn-large btn-primary" %>
  <%= link_to "Lend", location_item_lend_path(@location, @item), :class => "btn btn-large btn-primary" %>
  <%= link_to 'Edit', edit_location_item_path(@location, @item), :class => "btn btn-large btn-primary" %>
</div>