config/routes.rb
RedcrossTrackr::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :chapters
  resources :locations do
    resources :items do
      match "give/" => "items#give", :as => :give
      match "lend/" => "items#lend", :as => :lend
    end
  end

  root :to => 'locations#index'
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_paranoid
  geocoded_by :full_address
  after_validation :geocode

  attr_accessible :address, :address2, :city, :state_id, :zip,
                  :name, :description, :chapter_id, :state,
                  :contact_name, :contact_phone,
                  :national_shelter_system_identifier,
                  :picture, :picture_cache, :remove_picture

  attr_accessible :address, :address2, :chapter_id, :city, :contact_name, :contact_phone, :name, :national_shelter_system_identifier, :state_id, :zip, :chapter

  validates_presence_of :name, :address, :city, :state, :zip, :chapter
  validates_uniqueness_of :national_shelter_system_identifier, :allow_blank => true

  belongs_to :state
  belongs_to :chapter
  has_many :items, :foreign_key => "current_location_id"

  before_destroy :abort_delete_if_location_has_items

  mount_uploader :picture, PictureUploader

  def full_address
    [address, address2, city, state.name, zip].compact.join(" ")
  end

  def contact?
    contact_name.present? or contact_phone.present?
  end

  def number_of_items_of_type(item_type_definition)
    items.of_type(item_type_definition).sum("quantity")
  end

private
  def abort_delete_if_location_has_items
    return false if items.any?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def edit
    @location = Location.find(params[:id])
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @location = Location.find(params[:id])

    if @location.destroy
      redirect_to locations_url
    else
      redirect_to edit_location_path(@location), alert: "Can't delete this location because it has items attached to it."
    end
  end
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %>
    <%= f.collection_select :state_id, State.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :zip %>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :contact_name %>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %>
    <%= f.phone_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :national_shelter_system_identifier %>
    <%= f.text_field :national_shelter_system_identifier %>
  </div>
  <div class="field">
    <%= f.label :chapter_id %>
    <%= f.collection_select :chapter_id, Chapter.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :picture %>
    <%= image_tag(@location.picture_url(:thumbnail), :alt => @location.name) if @location.picture.present? %>
    <%= f.hidden_field :picture_cache %>
    <%= f.file_field :picture %>
  </div>

  <% unless @location.new_record? %>
    <%= link_to 'Delete', @location, :class => "delete btn btn-danger btn-large", method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <div class="actions two">
    <% if @location.new_record? %>
      <%= f.submit "Create", :class => "btn btn-primary btn-large" %>
      <%= link_to "Cancel", locations_path, :class => "btn btn-classy btn-large" %>  
    <% else %>
      <%= f.submit "Update", :class => "btn btn-primary btn-large" %>
      <%= link_to "Cancel", @location, :class => "btn btn-classy btn-large" %>
    <% end %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h3>Edit location</h3>

<%= render 'form' %>

app/views/locations/index.html.erb
<div class="location-title cf">
	<h4>Choose a location</h4>
	<div class="actions">
	  <%= link_to 'Add Location', new_location_path, :class => "btn btn-large btn-primary" %>
	</div>
</div>

<% @locations.each do |location| %>
  <%= link_to location, :class => "location cf #{cycle :even, :odd}", :data => { :lat => location.latitude, :lng => location.longitude } do %>
    <%= (image_tag location.picture_url(:thumbnail), :alt => location.name) if location.picture.present? %>
    <div class="location-details cf">
    	<div class="location-name"><%= location.name %></div>
    	<div class="location-chapter"><%= location.chapter.name %> Chapter</div>

    	<div class="address">
    	  <div class="street"><%= location.address %></div>
    	  <div class="street2"><%= location.address2 %></div>
    	  <div class="city-sate-zip"><%= location.city %>, <%= location.state.name %> <%= location.zip %></div>
    	</div>
    </div>

    <% if location.contact? %>
      <div class="contact">
        <%= location.contact_name %> <%= number_to_phone location.contact_phone %>
      </div>
    <% end %>
  <% end %>
<% end %>

<div class="map"></div>

app/views/locations/new.html.erb
<h3>Add location</h3>

<%= render 'form' %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="location cf" data-lat="<%= @location.latitude %>" data-lng="<%= @location.longitude %>">
  <div class="location-title cf">
  	<h4><%= @location.name %></h4>
  	<a href="#" class="info" rel="popover" data-placement="bottom" data-title="<%= @location.name %>">info</a>
    <div class="actions two cf">
      <%= link_to 'Edit', edit_location_path(@location), :class => "btn btn-large btn-primary" %>
      <%= link_to "Add Item", new_location_item_path(@location), :class => "btn btn-large btn-primary" %>
    </div>
  </div>
  <div class="details-wrapper cf">
  	<div class="details">
  		<%= (image_tag @location.picture_url(:thumbnail), :alt => @location.name) if @location.picture.present? %>
  	  <div class="address">
  	    <%= @location.address %>
  	    <%= @location.address2 %>
  	    <%= @location.city %>, <%= @location.state.name %> <%= @location.zip %>
  	  </div>
  	
  	  <div class="contact">
  	    <%= @location.contact_name %>
  	    <%= number_to_phone @location.contact_phone %>
  	  </div>
  	
  	  <p>
  	    <b>National shelter system identifier:</b>
  	    <%= @location.national_shelter_system_identifier %>
  	  </p>
  	
  	  <p>
  	    <b>Chapter:</b>
  	    <%= @location.chapter.name %>
  	  </p>
  	</div>
  	<div class="map"></div>
  </div>

</div>

<div class="navbar cf">
  <div class="navbar-inner">
    <ul class="nav">
      <li class="active"><a href="#">Items</a></li>
      <li><a href="#">Vehicles & Trailers</a></li>
      <li><a href="#">People</a></li>
    </ul>
  </div>
</div>

<%#= link_to "Move", move_location_items_path(@location) %>
<%#= link_to "Lend", lend_location_items_path(@location) %>

<div class="category">
	<span class="category-name">Items</span>
</div>

<div class="items cf">
  <% if @location.items.individuals.each do |item| %>
    <div class="item cf ">
      <%= (image_tag item.picture_url(:thumbnail), :alt => item.name ) if item.picture.present? %>
      <div class="item-details cf">
        <%= link_to item.name, [@location, item], :class => "item-name"%>
        <%#= item.item_type_definition.name %>
      	<span class="item-quantity">Quantity: <%= item.quantity %></span>
      	<span class="item-container">Container: <%= item.container.name if item.container %></span>
      	<%#= item.home_location.name unless item.at_home? %>
      </div>
    </div>
  <% end.empty? %>
    <div class="sorry">
      There are no items at this location
    </div>
  <% end %>
</div>

<div class="category">
	<span class="category-name">Vehicles & Trailers</span>
</div>

<div class="containers cf">
  <% if @location.items.containers.each do |container| %>
    <div class="item cf">
      <%= image_tag container.picture_url(:thumbnail), :alt => container.name %>
      <div class="item-details cf">
      <%= link_to container.name, [@location, container], :class => "item-name" %>
      <%= container.item_type_definition.name %>
      <span class="item-quantity">Quantity:<%= container.quantity %></span>
      <span class="item-container"><%= container.container.name if container.container %></span>
      <%= (container.home_location.name unless container.at_home?) if container.home_location %>
      </div>
    </div>
  <% end.empty? %>
    <div class="sorry">
      There are no items at this location
    </div>
  <% end %>
</div>