config/routes.rb
RedcrossTrackr::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :chapters
  resources :locations do
    resources :items do
      match "give/" => "items#give", :as => :give
      match "lend/" => "items#lend", :as => :lend
    end
  end

  root :to => 'locations#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrossTrack</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAiAYsEi7meP_hcCD4SxOhlkaUGMGqIvKw&sensor=true" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <link rel="apple-touch-icon-precomposed" href="<%= image_path('ios/red-cross-icon-57.png') %>" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<%= image_path('ios/red-cross-icon-114.png') %>" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<%= image_path('ios/red-cross-icon-72.png') %>" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<%= image_path('ios/red-cross-icon-144.png') %>" />
  <!-- <link rel="apple-touch-startup-image" href="<%= image_path('ios/start-up-iphone4.png') %>" />
  <link rel="apple-touch-startup-image" sizes="640x960" href="<%= image_path('ios/start-up-iphone4.png') %>" />
  <link rel="apple-touch-startup-image" sizes="640x1136" href="<%= image_path('ios/start-up-iphone5.png') %>" /> -->
  <!-- <link rel="apple-touch-startup-image" sizes="1024x748" href="img/splash-screen-1024x748.png" />
  <link rel="apple-touch-startup-image" sizes="768x1004" href="img/splash-screen-768x1004.png" /> -->
</head>
<body class="<%= controller_name %> <%= action_name %>">

<div class="page">
  <header class="cf">
  	<div class="logo"></div>
    <h1 class="name"><span>Cross</span>Track</h1>
    <% if current_user %>
      <div class="menu">Menu</div>
    <% end %>
    <ul class="nav cf">
      <% if current_user %>
        <li><%= link_to "Locations", locations_path %></li>
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <% if can?(:access, :rails_admin) %>
          <li><%= link_to "Admin", rails_admin_path, :class => "admin" %></li>
        <% end %>
      <% end %>
    </ul>
  </header>
  
  <div class="main cf">
    <div class="content cf">
      <% if flash[:notice] %>
        <div id="notice"><p><%= flash[:notice] %></p></div>
      <% end %>

      <% if flash[:alert] %>
        <div id="alert"><p><%= flash[:alert] %></p></div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>